spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          search-paths: respo
          username:
          password:
server:
  port: 8888

eureka:
  client:
    service-url:
      defalut-zone: http://localhost:8889/eureka/
